# Documentation: https://docs.brew.sh/Formula-Cookbook
#                https://rubydoc.brew.sh/Formula
# Based on Federico Terzi's approach: https://federicoterzi.com/blog/how-to-publish-your-rust-project-on-homebrew/
#
# AUTOMATED RELEASE PROCESS:
# This file is automatically updated by the CD pipeline when you push a tag:
# 1. Push a git tag: git tag v0.0.X && git push origin v0.0.X
# 2. GitHub Actions (cd-multiplatform.yml) triggers on tag push
# 3. Pipeline builds binaries, creates GitHub release with assets
# 4. update-homebrew-tap job automatically updates BA-CalderonMorales/homebrew-terminal-jarvis
# 5. Real Formula gets updated with correct version, URLs, and SHA256 checksums
#
# This file is automatically generated - the source template is in the main repository

class TerminalJarvis < Formula
  desc "A unified command center for AI coding tools"
  homepage "https://github.com/BA-CalderonMorales/terminal-jarvis"
  version "0.0.81"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BA-CalderonMorales/terminal-jarvis/releases/download/v0.0.81/terminal-jarvis-mac.tar.gz"
      sha256 "6212faea82f0a4316da6ce4f0d94b4d5985338a33f179d2b224a643ee2cc4812"
    elsif Hardware::CPU.arm?
      url "https://github.com/BA-CalderonMorales/terminal-jarvis/releases/download/v0.0.81/terminal-jarvis-mac.tar.gz"
      sha256 "6212faea82f0a4316da6ce4f0d94b4d5985338a33f179d2b224a643ee2cc4812"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/BA-CalderonMorales/terminal-jarvis/releases/download/v0.0.81/terminal-jarvis-linux.tar.gz"
      sha256 "72726865bd302d225fb73635b90e16216cef735d958dd92d54dd55547ba0d0fd"
    else
      # Fallback for other Linux architectures
      url "https://github.com/BA-CalderonMorales/terminal-jarvis/releases/download/v0.0.81/terminal-jarvis-linux.tar.gz"
      sha256 "72726865bd302d225fb73635b90e16216cef735d958dd92d54dd55547ba0d0fd"
    end
  end

  def install
    bin.install "terminal-jarvis"
    bin.install "jarvis"
  end

  test do
    system "#{bin}/terminal-jarvis", "--version"
  end
end
