# Documentation: https://docs.brew.sh/Formula-Cookbook
#                https://rubydoc.brew.sh/Formula
# Based on Federico Terzi's approach: https://federicoterzi.com/blog/how-to-publish-your-rust-project-on-homebrew/
#
# AUTOMATED RELEASE PROCESS:
# This file is automatically updated by the CD pipeline when you push a tag:
# 1. Push a git tag: git tag v0.0.X && git push origin v0.0.X
# 2. GitHub Actions (cd-multiplatform.yml) triggers on tag push
# 3. Pipeline builds binaries, creates GitHub release with assets
# 4. update-homebrew-tap job automatically updates BA-CalderonMorales/homebrew-terminal-jarvis
# 5. Real Formula gets updated with correct version, URLs, and SHA256 checksums
#
# This file is automatically generated - the source template is in the main repository

class TerminalJarvis < Formula
  desc "A unified command center for AI coding tools"
  homepage "https://github.com/BA-CalderonMorales/terminal-jarvis"
  version "0.0.68"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BA-CalderonMorales/terminal-jarvis/releases/download/v0.0.68/terminal-jarvis-mac.tar.gz"
      sha256 "8cc208a44f872a576bc9b0ebdf4c002cdc9668ef3b4b3ccb30ba07e5c9137ae3"
    elsif Hardware::CPU.arm?
      url "https://github.com/BA-CalderonMorales/terminal-jarvis/releases/download/v0.0.68/terminal-jarvis-mac.tar.gz"
      sha256 "8cc208a44f872a576bc9b0ebdf4c002cdc9668ef3b4b3ccb30ba07e5c9137ae3"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/BA-CalderonMorales/terminal-jarvis/releases/download/v0.0.68/terminal-jarvis-linux.tar.gz"
      sha256 "8eaee925f4211ea3658964994cd6f49861f96b06737b19336121d9a27a10df10"
    else
      # Fallback for other Linux architectures
      url "https://github.com/BA-CalderonMorales/terminal-jarvis/releases/download/v0.0.68/terminal-jarvis-linux.tar.gz"
      sha256 "8eaee925f4211ea3658964994cd6f49861f96b06737b19336121d9a27a10df10"
    end
  end

  def install
    bin.install "terminal-jarvis"
  end

  test do
    system "#{bin}/terminal-jarvis", "--version"
  end
end
