# Documentation: https://docs.brew.sh/Formula-Cookbook
#                https://rubydoc.brew.sh/Formula
# Based on Federico Terzi's approach: https://federicoterzi.com/blog/how-to-publish-your-rust-project-on-homebrew/
#
# AUTOMATED RELEASE PROCESS:
# This file is automatically updated by the CD pipeline when you push a tag:
# 1. Push a git tag: git tag v0.0.X && git push origin v0.0.X
# 2. GitHub Actions (cd-multiplatform.yml) triggers on tag push
# 3. Pipeline builds binaries, creates GitHub release with assets
# 4. update-homebrew-tap job automatically updates BA-CalderonMorales/homebrew-terminal-jarvis
# 5. Real Formula gets updated with correct version, URLs, and SHA256 checksums
#
# This file is automatically generated - the source template is in the main repository

class TerminalJarvis < Formula
  desc "A unified command center for AI coding tools"
  homepage "https://github.com/BA-CalderonMorales/terminal-jarvis"
  version "0.0.76"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BA-CalderonMorales/terminal-jarvis/releases/download/v0.0.76/terminal-jarvis-mac.tar.gz"
      sha256 "1fcee8f85b05a467202e1edf33cdf8dc28aff118a9fe3855628dbff3a82066e3"
    elsif Hardware::CPU.arm?
      url "https://github.com/BA-CalderonMorales/terminal-jarvis/releases/download/v0.0.76/terminal-jarvis-mac.tar.gz"
      sha256 "1fcee8f85b05a467202e1edf33cdf8dc28aff118a9fe3855628dbff3a82066e3"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/BA-CalderonMorales/terminal-jarvis/releases/download/v0.0.76/terminal-jarvis-linux.tar.gz"
      sha256 "bf3c3565b902cc0c5ab5c1ba2f1e552533b8a5a682ae0ba84d7be278d9fc6ea7"
    else
      # Fallback for other Linux architectures
      url "https://github.com/BA-CalderonMorales/terminal-jarvis/releases/download/v0.0.76/terminal-jarvis-linux.tar.gz"
      sha256 "bf3c3565b902cc0c5ab5c1ba2f1e552533b8a5a682ae0ba84d7be278d9fc6ea7"
    end
  end

  def install
    bin.install "terminal-jarvis"
  end

  test do
    system "#{bin}/terminal-jarvis", "--version"
  end
end
